WV_EMBEDDING_SIZE=64
SIAMESE_EMBEDDING_SIZE=128
MAX_WORDS=100
SIAMESE_BATCH_SIZE=32
SIAMESE_NUM_EPOCHS=50
KD_TREE_LEAF_SIZE=50
NUM_PAIRS_PER_GROUP=2
PYTABLES_INSERT_BATCH_SIZE=25000
NUM_THREADS=10
MIN_GROUP_SIZE=2
NUM_NEGATIVE_SAMPLES=10

DATA_FOLDER='data'
ITEMS_FILE='items.pkl'
PRODUCT_DATA_FILE='product_data.pkl'
SENT_TOKENS_FILE='sent_tokens.h5'
SENT_ARRAYS_FILE='sent_arrays.h5'
SIAMESE_MODEL_FILE='siamese_model_new.h5'
TRAIN_DATA_PAIRS_FILE='train_data_pairs.pkl'
TEST_DATA_PAIRS_FILE='test_data_pairs.pkl'
VALIDATION_DATA_PAIRS_FILE='validation_data_pairs.pkl'
WORD2IDX_FILE='word2idx_map.pkl'
WV_EMBEDDINGS_FILE='wv_embeddings.h5'
WV_KD_TREE_FILE='wv_kd_tree.pkl'
SIAMESE_KD_TREE_FILE='kd_tree.pkl'
WV_MODEL_FILE='wv_model.pkl'
GROUP_INDICES_FILE='group_indices.pkl'
SIAMESE_EMBEDDINGS_FILE='embeddings.h5'



